name: CI

on:
  pull_request:
  push:
    brances: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - env:
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
        run: |
          composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_PASSWORD
          composer install -n --prefer-dist --no-ansi --no-progress --no-suggest --no-scripts
      - run: vendor/bin/phpunit --testdox --colors=always
      - run: |
          npm install
          npm run test
